### PR TITLE
Make parser generic on position handling

### PR DESCRIPTION
**Pull request by newhoggy**

### CODE REVIEW

**Comment by newhoggy** [comment]
Don't know what to do about this warning though:

    SPECIALISE pragma on INLINE function probably won't fire: ‘conduitParser’

**Comment by newhoggy** [comment]
Full list of warnings:

```
/Users/jky/wrk/conduit/conduit-extra/Data/Conduit/Attoparsec/Tracking.hs:52:21: Warning:
    Ignoring unusable UNPACK pragma
      on the first argument of ‘ParseDelta’
    In the definition of data constructor ‘ParseDelta’
    In the data declaration for ‘ParseDelta’

/Users/jky/wrk/conduit/conduit-extra/Data/Conduit/Attoparsec/Tracking.hs:52:21: Warning:
    Ignoring unusable UNPACK pragma
      on the second argument of ‘ParseDelta’
    In the definition of data constructor ‘ParseDelta’
    In the data declaration for ‘ParseDelta’

/Users/jky/wrk/conduit/conduit-extra/Data/Conduit/Attoparsec/Tracking/Index.hs:64:1: Warning:
    SPECIALISE pragma on INLINE function probably won't fire: ‘conduitParser’

/Users/jky/wrk/conduit/conduit-extra/Data/Conduit/Attoparsec/Tracking/Index.hs:70:1: Warning:
    SPECIALISE pragma on INLINE function probably won't fire: ‘conduitParser’

/Users/jky/wrk/conduit/conduit-extra/Data/Conduit/Attoparsec/Tracking/Index.hs:76:1: Warning:
    SPECIALISE pragma on INLINE function probably won't fire: ‘conduitParserEither’

/Users/jky/wrk/conduit/conduit-extra/Data/Conduit/Attoparsec/Tracking/Index.hs:82:1: Warning:
    SPECIALISE pragma on INLINE function probably won't fire: ‘conduitParserEither’
[15 of 15] Compiling Data.Conduit.Attoparsec.Tracking.LineColumn ( Data/Conduit/Attoparsec/Tracking/LineColumn.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.5.0/build/Data/Conduit/Attoparsec/Tracking/LineColumn.o )

/Users/jky/wrk/conduit/conduit-extra/Data/Conduit/Attoparsec/Tracking/LineColumn.hs:64:1: Warning:
    SPECIALISE pragma on INLINE function probably won't fire: ‘conduitParser’

/Users/jky/wrk/conduit/conduit-extra/Data/Conduit/Attoparsec/Tracking/LineColumn.hs:70:1: Warning:
    SPECIALISE pragma on INLINE function probably won't fire: ‘conduitParser’

/Users/jky/wrk/conduit/conduit-extra/Data/Conduit/Attoparsec/Tracking/LineColumn.hs:76:1: Warning:
    SPECIALISE pragma on INLINE function probably won't fire: ‘conduitParserEither’

/Users/jky/wrk/conduit/conduit-extra/Data/Conduit/Attoparsec/Tracking/LineColumn.hs:82:1: Warning:
    SPECIALISE pragma on INLINE function probably won't fire: ‘conduitParserEither’
```

**Comment by newhoggy** [comment]
One of the warnings was fixed by replacing `INLINE` pragma with `INLINABLE` pragma.  Presumably, that's an improvement.

**Comment by newhoggy** [comment]
Okay, I removed the `UNPACK` pragma as well, since GHC isn't going to be able to help us here anyway.

**Comment by newhoggy** [comment]
Now includes unit tests.  PR is good to go.

**Comment by newhoggy** [comment]
Also, I did not change the original `Attoparsec` module to avoid compatibility issues.

**Comment by newhoggy** [comment]
It turns out I can actually put this code in a separate package.

See https://hackage.haskell.org/package/conduit-tokenize-attoparsec

Shall I close this pull request then?

**Comment by newhoggy** [comment]
I've tidied up the code some more and published it as a separate library.

https://hackage.haskell.org/package/conduit-tokenize-attoparsec

**Comment by snoyberg** [comment]
If this is already living in another library, it wouldn't be a good idea to merge in conflicting modules here. Thanks for writing this, closing.

**Pull request closed without merging**
