### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ra1u**

### CODE REVIEW

**Comment by snoyberg** [comment]
Is this necessary to get the example to compile?

**Comment by ra1u** [comment]
that was for me -> error
pg.hs:12:5: Not in scope: ‘runResourceT’

my version is 
conduit: 1.2.5.1
conduit-combinators: 1.0.3
but i havent checked other examples

**Comment by snoyberg** [comment]
It would be better to import from Control.Monad.Trans.Resource

**Comment by ra1u** [comment]
I can check other examples and update PR

**Comment by snoyberg** [comment]
Looks like this change has already made it to master.

**Pull request closed without merging**
