### PR TITLE
Added a strictness footnote.

### PR DESCRIPTION
**Pull request by reactormonk**
There's probably a better way to do this, do you have an idea?

### CODE REVIEW

**Comment by snoyberg** [comment]
I think this comment is too vague. I'd rather point to another source on the difference between WHNF and NF. The conversation we've been having has encouraged me to write a blog post on the subject. Maybe that will help clear things up (and be a good source to link to).

**Comment by reactormonk** [comment]
Would it be overkill/wrong approach to add `NFData` to most of the conduit functions?

**Comment by snoyberg** [comment]
It's conceivable to add a set of NFData functions, but it wouldn't be a
replacement for the existing functions. NFData introduces both an extra
constraint, and extra overhead. Using strict data types is usually the
right answer in these cases.

**Comment by snoyberg** [comment]
Closing this for now due to the concerns I cited. If you have a more moderate wording, a new PR is welcome.

**Pull request closed without merging**
